### ISSUE TITLE
action connect & disconnect should be protected by passport policy

### ISSUE THREAD

**Issue by JAertgeerts** [jaumard/trailpack-passport#143]
for both actions connect & disconnect, it doesn't make sense they're available without Passport.jwt or Passport.session. Right now, there doesn't seem to be a clean way to set it like that.
Now, I'm overriding AuthController with:
```
  callbackAuth(req, res) {
    super.callback(req, res)
  }
```
and adding below to policies.js 
 ```
 AuthController: {
    callbackAuth: [
      'Passport.jwt'
    ]
  }
```
and routes.js
```
  {
    method: 'GET',
    path: '/api/v1/auth/{provider}/connect',
    handler: 'AuthController.callbackAuth'
  },
  {
    method: 'GET',
    path: '/api/v1/auth/{provider}/disconnect',
    handler: 'AuthController.callbackAuth'
  }
```

**Comment by jaumard** [comment]
I don't remember how it's working but connect can be called without any connected/session user as the /connect will create the user if it doesn't exist (if I remember correctly). /disconnect yeah it doesn't make sense to have it without a user... In order to do that I need to refactor the callback method and extract disconnect (and maybe connect if it doesn't create any user) to put it in a method

**Comment by JAertgeerts** [comment]
Well, but if you just call the provider route without connect / disconnect - it does that already for you. So it would make sense to separate out connecting & disconnecting?

**Comment by jaumard** [comment]
I just check the code and I check if req.user is present so yes we can add this policy by default and do the fix you did under the controller
