### ISSUE TITLE
Having the jwt strategy activated when doing login it does not store the token generated in the tokens field of the passport table

### ISSUE THREAD

**Issue by jesus-ibanez** [jaumard/trailpack-passport#188]
Store the token generated could help to invalidate it when user logout of application in order to gain more security.

Approach:
- Login, the token must be stored into the passport table
- At any CRUD operation, the token must be get from the DB and validated before any action
- Logout, the token must be invalidated and deleted from passport table

**Comment by JAertgeerts** [comment]
@jesus-ibanez this would no longer make your tokens stateless. the idea behind jwt is that you can store and sign that in the token rather than keeping it somewhere in a database and having to call it without reason. 

Another way to approach this would be following the practices described here: https://stackoverflow.com/questions/21978658/invalidating-json-web-tokens

Keep a list of invalid tokens, keep the token lifecycle short and rotate often (expiry date) and store it on the client & remove it on logout.

**Comment by jaumard** [comment]
Keeping a list of invalid token is worse in my opinion because you also check at every request that it's not under the black list and you also have a growing list in your database that you need to clean with some cron task... 

For the short lifecycle I agree but it need to be used with an oauth2 server that stock the refresh token into database, and users can manage refresh tokens if they are leaked. That my best solution about this and I think that will be the one chosen here. 

I don't want to have one more request in database for each http request just to test that the token is ok. @jesus-ibanez if you want what you describe you can already doing it with a custom policy in front of the Passport.jwt policy.

**Comment by jaumard** [comment]
Closing this issue as the best solution is not to modify this trailpack but to use oauth2 or a custom policy
