### ISSUE TITLE
500 error on duplicate username with trailpack-mongoose

### ISSUE THREAD

**Issue by ricick** [jaumard/trailpack-passport#207]
Local auth currently returns a 500 error instead of a 409 on registration if you try to resgiter a duplicate username with trailpack-mongoose.

I managed to patch this in my app by adding the following to line 51 of api/controllers/AuthContoller
```
        }
        else if(err.name === 'MongoError' && err.code == 11000){
          res.status(409).json({error: err.message || err})
        } else {
```
However this feels really mongoose specific code in a database agnostic part of the application. Is there a better place/way to be doing this?

**Comment by ricick** [comment]
It's also the case that mongoose validation errors are being returned as 500 server errors instead of 400 bad requests.

At the moment I'm monkey patching the AuthController.callback function after the app starts up to get around this, but it might be an idea to add a optional custom error handler function to passport config that is then called when the trailpack can't interpret an error itself, instead of defaulting to sending a 500 error.

**Comment by jaumard** [comment]
For me this is an update that need to be done under trailpack-mongoose, it's not possible for all trailpack to deal with all kind of ORM errors, for sequelize for example it change the error on the fly to have a common error across ORM (https://github.com/trailsjs/trailpack-sequelize/blob/master/api/services/FootprintService.js#L9) same should be done for mongoose.

If you want to patch more cleanly just create a AuthController that extends the AuthController of this trailpack and just override the callback method to patch it ;) 

But the fix of this problem is definitely not on this module. Feel free to contribute to trailpack-mongoose or create the issue there :) thanks
