### ISSUE TITLE
feature-request(form/data): Add the support of form/data

### ISSUE THREAD

**Issue by maissani** [jaumard/trailpack-passport#38]
# Feature Request : 
### Description:
Enable the support of form/data,
In fact for the moment trailpack-passport support application/json well but do not catch post variables when data is send with form/data.

The Result should be the support of theses request: 

### Register
```
POST /auth/local/register HTTP/1.1
Host: localhost:3000
Cache-Control: no-cache
Content-Type: multipart/form-data;
Content-Disposition: form-data; name="username"
foo
Content-Disposition: form-data; name="password"
bar
```
### login
```
POST /auth/local HTTP/1.1
Host: localhost:3000
Cache-Control: no-cache
Content-Type: multipart/form-data;
Content-Disposition: form-data; name="username"
foo
Content-Disposition: form-data; name="password"
bar
```
### Logout
Sould not be changed because it works well and doesn't need any changes

**Comment by jaumard** [comment]
`trailpack-express` come with `body-parser` who doesn't parse `form-data`, I make tests with `application/x-www-form-urlencoded` and all is working. It will not working with `form-data` because `trailpack-express` need to be configured (with multer for example) do process it. Then `trailpack-passport`  should work without any modifications...

**Comment by jaumard** [comment]
@maissani I think finally I can't do anything about this, it have to work if express was well configured

**Comment by jaumard** [comment]
An error is throw now if `password` was not present when call `register`. Like this user will know the trailpack doesn't receive the data and will more look into express configurations
